name: Test

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: "Test go ${{ matrix.go_version }} on ${{ matrix.platform }}"
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
        go_version:
          # Test the two currently supported releases.
          # (https://go.dev/doc/devel/release#policy).
          - stable
          - oldstable

    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go_version }}
          check-latest: true

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build
        run: go build -v

      - name: Single Test
        run: go test -v

      # Run the tests again 100 times without verbose.
      - name: Many Tests
        run: go test -count=100 -timeout=30s

  crosscompile:
    name: Run ./test_crosscompile.sh
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run ./test_crosscompile.sh
        run: ./test_crosscompile.sh

  notify:
    if: always()
    needs:
      - test
      - crosscompile
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification with workflow result.
        uses: ScribeMD/slack-templates@0.6.38
        with:
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: C0727A4EXGB 
          template: result
          results: "${{ join(needs.*.result, ' ') }}"
